### ISSUE TITLE
가짜 토스 페이먼츠 서버 실행 문의

### ISSUE THREAD

**Issue by imjlk** [samchon/payments#19]
## Question

https://github.com/samchon/fake-toss-payments-server/blob/2efc253d4420615f49e7a5b179fabb6903566736/README.md?plain=1#L108

README.md 내용대로 해당 저장소를 복제하여 모듈 인스톨, 빌드 후 실행 하려하니 아래와 같이 에러가 발생합니다

```shell
$ npm run start

> fake-toss-payments-server@1.0.2 start
> pm2 start lib/executable/server.js -i 1 --name fake-toss-payments-server --wait-ready --listen-timeout 120000 --kill-timeout 15000 --

[PM2][ERROR] File ecosystem.config.js not found
```

별도로 src\FakeTossConfiguration.ts 파일에서 수정한 내용은 없는데, 추가 설정이 필요한 걸까요? 관련 파일에 대한 정보를 찾지 못하여 질문 남깁니다.

**Comment by samchon** [comment]
@imjlk 제보 감사합니다.

pm2 명령어 가장 뒷 쪽에 쓸데없이 `--` 가 하나 더 들어가서 생기는 버그였습니다. 

해결하였으니, pull 받으시고 다시 `npm run start` 명령어 실행해보세요.
